<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\Puppet.Common.targets" />

	<PropertyGroup>
		<RootNamespace>Puppet.Core.Console</RootNamespace>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Description>Puppet.Core Console 子项目：进程状态描述、stdin/stdout 交互。</Description>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Puppet.Core\Puppet.Core.csproj" />
	</ItemGroup>

</Project>
